# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4249605032ce8b461b62c44684262051f3a6f0e341df63a70ce266260ca660f75a6a54d5ab88ee476a33239276227bb3435d3f2bf4485333427d42538e8dd1ec

test:
  secret_key_base: 8bb7a02de72eb9d4dd0c8022396e92005fcae84c5953885c49ae154aebfc23390ab726eab9fb9866a22dca45418c3a02445ca4c101a1f6070cc614d47acf1970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
